# Generated by Django 2.2.3 on 2019-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('kilometros', models.PositiveIntegerField()),
                ('bastidor', models.CharField(max_length=25)),
                ('asegurado', models.BooleanField()),
                ('aseguradora', models.CharField(max_length=50)),
                ('num_poliza', models.CharField(max_length=20)),
                ('tipo_motor', models.CharField(max_length=50)),
                ('placa_oval', models.CharField(max_length=15)),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
