# Generated by Django 2.2.3 on 2019-07-07 19:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('razon_social', models.CharField(max_length=60)),
                ('grupo', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=50)),
                ('cod_postal', models.CharField(max_length=5)),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('movil', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('web', models.URLField(max_length=60)),
                ('observaciones', ckeditor.fields.RichTextField(verbose_name='observaciones')),
                ('tarifa', models.CharField(max_length=3)),
                ('tipo_iva', models.SmallIntegerField(default=0)),
                ('descuento', models.SmallIntegerField(default=0)),
                ('descuento_pp', models.SmallIntegerField(default=0)),
                ('rec_eq', models.CharField(max_length=3)),
                ('cuenta_contable', models.CharField(max_length=22)),
                ('cuenta_ingresos', models.CharField(max_length=22)),
                ('cuenta_retencion', models.CharField(max_length=22)),
                ('cuenta_caja', models.CharField(max_length=22)),
                ('dias_de_pago', models.SmallIntegerField(default=0)),
                ('banco', models.CharField(max_length=22)),
                ('dir_banco', models.CharField(max_length=60)),
                ('ccc', models.CharField(max_length=20)),
                ('forma_pago', models.CharField(max_length=1)),
                ('medio_pago', models.CharField(max_length=20)),
                ('credito', models.SmallIntegerField(default=0)),
                ('limite_riesgo', models.SmallIntegerField(default=0)),
                ('liquidacion', models.SmallIntegerField(default=0)),
                ('comisionista', models.CharField(max_length=20)),
                ('comision', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cod_cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Cliente'),
        ),
    ]
