# Generated by Django 2.2.3 on 2019-07-07 19:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20190707_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cif', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=40)),
                ('persona_contacto', models.CharField(max_length=20)),
                ('movil', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('web', models.URLField(max_length=60)),
                ('cod_postal', models.CharField(max_length=5)),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=22)),
                ('dir_banco', models.CharField(max_length=60)),
                ('ccc', models.CharField(max_length=20)),
                ('forma_pago', models.CharField(max_length=1)),
                ('medio_pago', models.CharField(max_length=20)),
                ('cuenta_contable', models.CharField(max_length=22)),
                ('cuenta_ingresos', models.CharField(max_length=22)),
                ('cuenta_retencion', models.CharField(max_length=22)),
                ('cuenta_caja', models.CharField(max_length=22)),
                ('irpf', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('saldo', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('intracomunitario', models.BooleanField()),
                ('observaciones', ckeditor.fields.RichTextField()),
                ('alarmas', models.CharField(max_length=5)),
                ('nueva_alarma', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='movil',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=80)),
                ('proveedor', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('stockable', models.BooleanField()),
                ('fecha_compra', models.DateTimeField()),
                ('reservados', models.IntegerField()),
                ('stock_optimo', models.IntegerField()),
                ('pedido_proveedor', models.IntegerField()),
                ('observaciones', ckeditor.fields.RichTextField()),
                ('referencia', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=1)),
                ('marca', models.CharField(max_length=30)),
                ('familia', models.CharField(max_length=1)),
                ('subfamilia', models.CharField(max_length=1)),
                ('precio_compra', models.IntegerField()),
                ('descuento_compra', models.IntegerField()),
                ('precio_coste', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('precio_medio', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('beneficio', models.IntegerField()),
                ('pvp_iva', models.IntegerField()),
                ('cod_proveedor', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Proveedor')),
            ],
        ),
    ]
