# Generated by Django 2.2.4 on 2019-08-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20190818_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='cliente',
            new_name='cod_cliente',
        ),
    ]
