# Generated by Django 2.2.5 on 2019-09-22 12:15

from django.db import migrations, models
import vehiculos.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20190819_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=vehiculos.models.custom_upload_to),
        ),
    ]
