# Generated by Django 2.2.1 on 2019-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_ficha_tecnica_reparacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['articulo']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
    ]
