# Generated by Django 2.2.1 on 2019-07-12 19:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_auto_20190711_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cod_proveedor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='ficha_tecnica',
            name='cod_vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='cod_cliente',
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(to='vehiculos.Proveedor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='vehiculos',
            field=models.ManyToManyField(to='vehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica',
            name='vehiculo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
