# Generated by Django 2.2.5 on 2019-09-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_auto_20190923_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='reparacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Reparacion'),
        ),
    ]
