# Generated by Django 2.2.4 on 2019-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_auto_20190712_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometros',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
