# Generated by Django 2.2.5 on 2019-09-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_auto_20190923_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='reparacion',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
    ]
