# Generated by Django 2.2.4 on 2019-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_auto_20190815_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='asegurado',
            field=models.BooleanField(null=True),
        ),
    ]
