# Generated by Django 2.2.5 on 2019-10-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_auto_20190927_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Cliente'),
        ),
    ]
