# Generated by Django 2.2.5 on 2019-10-04 09:41

from django.db import migrations, models
import vehiculos.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_auto_20191001_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=vehiculos.models.custom_upload_to),
        ),
    ]
