# Generated by Django 2.2.4 on 2019-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_auto_20190815_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.CharField(max_length=20),
        ),
    ]
