# Generated by Django 2.2.5 on 2019-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='asegurado',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='kilometros',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='libro_mantenimiento',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='libro_mto',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
