# Generated by Django 2.2.5 on 2019-10-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_auto_20191004_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Proveedor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, null=True, to='vehiculos.Vehiculo'),
        ),
    ]
