# Generated by Django 2.2.5 on 2019-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0015_remove_articulo_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
